create Database POP_BD;
use POP_BD;

CREATE TABLE bandas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE integrantes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    banda_id INT NOT NULL,
    FOREIGN KEY (banda_id) REFERENCES bandas(id)
);

CREATE TABLE musicas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    banda_id INT NOT NULL,
    FOREIGN KEY (banda_id) REFERENCES bandas(id)
);

Create TABLE Logins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
)


-- Inserir bandas
INSERT INTO bandas (nome) VALUES
('Bee Gees'),
('ABBA'),
('Queen'),
('The Beatles'),
('Nirvana'),
('Evanescence'),
('Maroon 5'),
('Coldplay'),
('Bon Jovi'),
('Red Hot Chili Peppers');

-- Inserir integrantes
INSERT INTO integrantes (nome, banda_id) VALUES
('Barry Gibb', 1),
('Robin Gibb', 1),
('Maurice Gibb', 1),
('Agnetha Fältskog', 2),
('Björn Ulvaeus', 2),
('Benny Anderson', 2),
('Anni-Frid Lyngstad', 2),
('Freddie Mercury', 3),
('Brian May', 3),
('John Deacon', 3),
('Roger Taylor', 3),
('John Lennon', 4),
('Paul McCartney', 4),
('George Harrison', 4),
('Ringo Starr', 4),
('Curt Cobain', 5),
('Dave Grohl', 5),
('Krist Novoselic', 5),
('Pat Smear', 5),
('Troy McLawhorn', 6),
('Tim McCord', 6),
('Emma Anzai', 6),
('Will Hunt', 6),
('Adam Levine', 7),
('James Valentine', 7),
('PJ Morton', 7),
('Mickey Madden', 7),
('Sam Farrar', 7),
('Jesse Carmichael', 7),
('Matt Flynn', 7),
('Chris Martin', 8),
('Jonny Buckland', 8),
('Guy Berryman', 8),
('Will Champion', 8),
('Phil Harvey', 8),
('Jon Bon Jovi', 9),
('David Bryan', 9),
('Tico Torres', 9),
('Phil X', 9),
('Hugh McDonals', 9),
('Anthony Kiedis', 10),
('Flea', 10),
('Chad Smith', 10),
('John Frusciante', 10);

-- Inserir músicas
INSERT INTO musicas (nome, banda_id) VALUES
('How Deep Is Your Love', 1),
('Stayin\' Alive', 1),
('I Started a Joke', 1),
('Wish You Were Here', 1),
('More Than a Woman', 1),
('For Whom The Bell Tolls', 1),
('Too Much Heaven', 1),
('Night Fever', 1),
('To Love Somebody', 1),
('Tragedy', 1),
('Dancing Queen', 2),
('Slipping Through My Fingers', 2),
('The Winner Takes It All', 2),
('Mamma Mia', 2),
('Lay All Your Love On Me', 2),
('Gimme! Gimme! Gimme! (A Man After Midnight)', 2),
('I Have a Dream', 2),
('Super Trouper', 2),
('Chiquitita', 2),
('SOS', 2),
('Bohemian Rhapsody', 3),
('Somebody to Love', 3),
('We Will Rock You', 3),
('We Are the Champions', 3),
('Don\'t Stop Me Now', 3),
('Another One Bites the Dust', 3),
('Radio Ga Ga', 3),
('Killer Queen', 3),
('Under Pressure', 3),
('I Want to Break Free', 3),
('Hey Jude', 4),
('Let It Be', 4),
('Yesterday', 4),
('A Day in the Life', 4),
('Come Together', 4),
('Something', 4),
('Here Comes the Sun', 4),
('Help!', 4),
('Strawberry Fields Forever', 4),
('All You Need Is Love', 4),
('Smells Like Teen Spirit', 5),
('Come as You Are', 5),
('In Bloom', 5),
('Heart-Shaped Box', 5),
('All Apologies', 5),
('About a Girl', 5),
('The Man Who Sold the World', 5),
('Aneurysm', 5),
('Rape Me', 5),
('Lithium', 5),
('Bring Me to Life', 6),
('My Immortal', 6),
('Going Under', 6),
('Call Me When You\'re Sober', 6),
('Lithium', 6),
('Everybody\'s Fool', 6),
('Tourniquet', 6),
('What You Want', 6),
('The Game is Over', 6),
('W asted on You', 6),
('She Will Be Loved', 7),
('Sugar', 7),
('Girls Like You', 7),
('Moves Like Jagger', 7),
('This Love', 7),
('Payphone', 7),
('One More Night', 7),
('Animals', 7),
('Maps', 7),
('Memories', 7),
('VivaLaVida', 8),
('TheScientist', 8),
('FixYou', 8),
('Yellow', 8),
('Clocks', 8),
('Paradise', 8),
('Shiver', 8),
('A SkyFullOfStars', 8),
('AdventureOfALifetime', 8),
('HymnForTheWeekend', 8),
('Livin\'OnAPrayer', 9),
('It\'sMyLife', 9),
('Always', 9),
('YouGiveLoveABadName', 9),
('BedOfRoses', 9),
('WantedDeadOrAlive', 9),
('I\'llBeThereForYou', 9),
('Runaway', 9),
('BadMedicine', 9),
('BornToBeMyBaby', 9),
('Californication', 10),
('Scar Tissue', 10),
('Can\'t Stop', 10),
('Under The Bridge', 10),
('Otherside', 10),
('By The Way', 10),
('Snow (Hey Oh)', 10),
('Dark Necessities', 10),
('Around The World', 10),
('The Zephyr Song', 10);